apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-namespace-scope-operator
  namespace: {{ .Values.operator_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWave | default "-15" | quote }} 
spec:
  channel: v3
  installPlanApproval: Automatic
  name: ibm-namespace-scope-operator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace


---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.operator_namespace }} 
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWave | default "-5" | quote }}     
spec:
  {{- toYaml .Values.spec | nindent 2 }}


  
