apiVersion: databases.cpd.ibm.com/v1
kind: Db2oltpService       
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.cpd_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWave | default "-3" | quote }}  
spec:  
  license:
    accept: true
    license: {{ .Values.license }}